In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv("C:\\Users\\SAIF04KHAN\\Desktop\\AmazonSageMakerCourse\\pipeline\\house_price_prediction_linear_reg_deployment\\house_price.csv")

In [3]:
df.head()

Unnamed: 0      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0          37  Bommanahalli    3           1   3000           1      3  28000
1          43  Bommanahalli    3           1   1650          10      0  18000
2          12    Whitefield    2           0   1000           5      3  16400
3           8    Whitefield    3           0   1600           1      9  27000
4           9    Whitefield    2           1   1200           5      1  20000

In [4]:
df =df.iloc[:,1:]

In [5]:
df.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0  Bommanahalli    3           1   3000           1      3  28000
1  Bommanahalli    3           1   1650          10      0  18000
2    Whitefield    2           0   1000           5      3  16400
3    Whitefield    3           0   1600           1      9  27000
4    Whitefield    2           1   1200           5      1  20000

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score


In [7]:
label_enc = LabelEncoder()

In [8]:
df.iloc[:,0] = label_enc.fit_transform(df.iloc[:,0])

In [9]:
df

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0           0    3           1   3000           1      3  28000
1           0    3           1   1650          10      0  18000
2           1    2           0   1000           5      3  16400
3           1    3           0   1600           1      9  27000
4           1    2           1   1200           5      1  20000
5           1    3           1   1760           5      8  39500
6           1    3           1   1870          10      3  35000
7           1    3           0   2200           1     10  42000
8           1    3           0   2100           1      7  28000
9           1    3           0   1704           5     13  35000
10          1    2           0   1326           1      3  21000
11          1    2           0   1000           5      3  16400
12          1    2           0   1088           5      1  14000
13          0    3           0   1744           1      2  22000
14          1    2           0   1060           5      1  16000
15          0    2           0    950           5      1  14000
16          1    3           0   3155           1      1  45000
17          0    3           1   3000           1      3  28000
18          1    2           0   1280           5      3  23000
19          1    3           0   3155           1      1  45000
20          1    3           1   1760           5      8  39500
21          0    2           0   1033           5      0  16500
22          0    2           0   1135          10      2  16000
23          0    3           1   1471          10      3  21000
24          1    2           0   1000           1      3  18000
25          1    3           0   2292           5     12  39000
26          1    2           0   1290           1     10  26000
27          1    2           0   1290           1     10  26000
28          0    2           0   1089           5      2  15500
29          0    3           1   1250           1      1  20000
..        ...  ...         ...    ...         ...    ...    ...
970         0    2           0    950           5      1  14000
971         1    2           1   1245           5      1  25000
972         1    2           1   1200           5      1  20000
973         0    2           0   1033           5      0  16500
974         1    2           0   1060           1      1  17000
975         1    2           0   1280           5      3  23000
976         1    2           0   1290           1     10  26000
977         0    3           0   1744           1      2  22000
978         0    3           0   1375           5      3  19000
979         0    2           1    767           1      3  16000
980         1    2           0   1000           1      3  18000
981         0    2           1   1089           5      2  15500
982         0    2           0   1400           5      2  22000
983         0    3           1   1250           1      1  20000
984         1    3           0   1600           1      9  27000
985         1    2           0   1326           1      3  21000
986         1    3           0   2180           1     11  35000
987         1    2           0   1333           1      3  26000
988         1    3           0   2180           1     11  35000
989         1    2           0   1326           1      3  21000
990         1    3           0   1600           1      9  27000
991         1    2           0   1088           5      1  14000
992         0    3           1   1460           1      2  25000
993         1    2           0   1290           1     10  26000
994         1    2           0   1060           1      1  17000
995         0    3           1   1460           1      2  25000
996         1    3           0   2100           1      7  28000
997         0    2           0   1033           5      0  16500
998         0    3           0   1500          10      1  22000
999         1    3           1   1768           5     11  30000

[1000 rows x 7 columns]

In [10]:
X = df.drop('Price', axis=1)
y = df['Price']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
reg = LinearRegression()

In [13]:
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
reg.coef_

array([4242.80338841, 2424.8337951 , 1009.00341089,    8.69832739,
        -53.88071786,  515.05412671])

In [15]:
reg.intercept_

345.83954901305697

In [16]:
reg.predict(X_test)

array([36437.21270929, 36437.21270929, 32032.23336471, 39767.54064765,
       36096.12513038, 20856.29988664, 16437.69374213, 20644.07896768,
       37710.95663224, 33646.98236396, 15559.40980186, 22463.57430929,
       16437.69374213, 19147.74126555, 21522.3820767 , 25755.8134102 ,
       33646.98236396, 30144.37515477, 13704.56869729, 19412.39670862,
       23766.45143838, 14552.25663529, 30223.62268991, 32032.23336471,
       20644.07896768, 19412.39670862, 21522.3820767 , 22305.12987045,
       36215.60817807, 33646.98236396, 17352.87349516, 15559.40980186,
       30223.62268991, 33681.13001124, 16437.69374213, 18954.42358091,
       20644.07896768, 16437.69374213, 36437.21270929, 19147.74126555,
       36096.12513038, 16437.69374213, 36096.12513038, 22463.57430929,
       19147.74126555, 19119.71097008, 20856.29988664, 30362.07456955,
       36437.21270929, 22305.12987045, 20644.07896768, 15428.69033124,
       17352.87349516, 21130.95734414, 22524.46260102, 18788.09494817,
      

In [17]:
import pickle as pk

In [18]:
with open('model.pkl','wb') as f:
    pk.dump(reg,f,protocol=2)

In [19]:
X_test.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
507         1    3           0   2180           1     11
818         1    3           0   2180           1     11
452         1    3           1   1760           5      8
368         1    3           0   3155           1      1
242         1    3           0   2200           1     10

In [20]:
reg.predict([[2,1,0,10000,1,19]])

array([107971.70171253])

In [21]:
df.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0         0    3           1   3000           1      3  28000
1         0    3           1   1650          10      0  18000
2         1    2           0   1000           5      3  16400
3         1    3           0   1600           1      9  27000
4         1    2           1   1200           5      1  20000